/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake;

import com.mycompany.snake.interfaces.Incrementer;

/**
 *
 * @author saliheany
 */
public class ScoreBoard extends javax.swing.JPanel implements Incrementer {

    /**
     * Creates new form ScoreBoard
     */
    private int score;
    
    public ScoreBoard() {
        initComponents();
        score = 0;
        incrementScore(0);
    }
    public void incrementScore(int increment) {
        score += increment;
        jLabel1.setText("Score: " + score);
    }
    @Override
    public void resetScore() {
        score = 0;
        incrementScore(0);
    }
    
    @Override
    public int getScore() {
        return score;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
